# Generated by Django 2.1.5 on 2019-02-12 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190210_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 17, 21, 44, 798019, tzinfo=utc)),
        ),
    ]
